version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./files/public_html:/code
            - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    php:
        image: php:7.1-fpm
        volumes:
            - ./files/public_html:/code
        links:
            - db
	
    db:
        image: mysql:5.7
        volumes:
        - "./files/.data/db:/var/lib/mysql"
        restart: always
        ports:
            - "3306:3306"
        environment:
         MYSQL_ROOT_PASSWORD: dbrootpass
         MYSQL_DATABASE: dbname
         MYSQL_USER: local
         MYSQL_PASSWORD: "!local!"


